name: sandbox
database_url: sqlite:sandbox.sqlite
targets:
  - maven
config:
   maven.url: http://maven.layer.com:1234/nexus
   maven.username: none
   maven.password: none
   db.dump_tables:
     - schema_migrations
